# Generated by Django 2.2.7 on 2019-11-14 23:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0002_auto_20191108_2147'),
        ('app', '0002_auto_20191108_1823'),
    ]

    operations = [
    ]
