# Generated by Django 2.2.7 on 2019-11-14 23:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0003_merge_20191114_2319'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='property',
            name='host',
        ),
    ]
